# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: building-pkg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import street_pkg_pb2 as street__pkg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='building-pkg.proto',
  package='com.building',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x62uilding-pkg.proto\x12\x0c\x63om.building\x1a\x10street-pkg.proto\"l\n\x0b\x42uildingPkg\x12\x15\n\rbuilding_name\x18\x01 \x01(\t\x12\x17\n\x0f\x62uilding_number\x18\x02 \x01(\t\x12-\n\x0estreet_details\x18\x03 \x01(\x0b\x32\x15.com.street.StreetPkgb\x06proto3'
  ,
  dependencies=[street__pkg__pb2.DESCRIPTOR,])




_BUILDINGPKG = _descriptor.Descriptor(
  name='BuildingPkg',
  full_name='com.building.BuildingPkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='building_name', full_name='com.building.BuildingPkg.building_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='building_number', full_name='com.building.BuildingPkg.building_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='street_details', full_name='com.building.BuildingPkg.street_details', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=162,
)

_BUILDINGPKG.fields_by_name['street_details'].message_type = street__pkg__pb2._STREETPKG
DESCRIPTOR.message_types_by_name['BuildingPkg'] = _BUILDINGPKG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildingPkg = _reflection.GeneratedProtocolMessageType('BuildingPkg', (_message.Message,), {
  'DESCRIPTOR' : _BUILDINGPKG,
  '__module__' : 'building_pkg_pb2'
  # @@protoc_insertion_point(class_scope:com.building.BuildingPkg)
  })
_sym_db.RegisterMessage(BuildingPkg)


# @@protoc_insertion_point(module_scope)
