# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg-tmpaddress.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import building_pkg_pb2 as building__pkg__pb2
import street_pkg_pb2 as street__pkg__pb2
import city_pkg_pb2 as city__pkg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pkg-tmpaddress.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14pkg-tmpaddress.proto\x1a\x12\x62uilding-pkg.proto\x1a\x10street-pkg.proto\x1a\x0e\x63ity-pkg.proto\"\x99\x01\n\rPkgTmpAddress\x12\x32\n\x0f\x62uilding_import\x18\x01 \x01(\x0b\x32\x19.com.building.BuildingPkg\x12,\n\rstreet_import\x18\x02 \x01(\x0b\x32\x15.com.street.StreetPkg\x12&\n\x0b\x63ity_import\x18\x03 \x01(\x0b\x32\x11.com.city.CityPkgb\x06proto3'
  ,
  dependencies=[building__pkg__pb2.DESCRIPTOR,street__pkg__pb2.DESCRIPTOR,city__pkg__pb2.DESCRIPTOR,])




_PKGTMPADDRESS = _descriptor.Descriptor(
  name='PkgTmpAddress',
  full_name='PkgTmpAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='building_import', full_name='PkgTmpAddress.building_import', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='street_import', full_name='PkgTmpAddress.street_import', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city_import', full_name='PkgTmpAddress.city_import', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=232,
)

_PKGTMPADDRESS.fields_by_name['building_import'].message_type = building__pkg__pb2._BUILDINGPKG
_PKGTMPADDRESS.fields_by_name['street_import'].message_type = street__pkg__pb2._STREETPKG
_PKGTMPADDRESS.fields_by_name['city_import'].message_type = city__pkg__pb2._CITYPKG
DESCRIPTOR.message_types_by_name['PkgTmpAddress'] = _PKGTMPADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PkgTmpAddress = _reflection.GeneratedProtocolMessageType('PkgTmpAddress', (_message.Message,), {
  'DESCRIPTOR' : _PKGTMPADDRESS,
  '__module__' : 'pkg_tmpaddress_pb2'
  # @@protoc_insertion_point(class_scope:PkgTmpAddress)
  })
_sym_db.RegisterMessage(PkgTmpAddress)


# @@protoc_insertion_point(module_scope)
