// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkg-tmpaddress.proto

public final class PkgTmpaddress {
  private PkgTmpaddress() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PkgTmpAddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PkgTmpAddress)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.building.BuildingPkg building_import = 1;</code>
     * @return Whether the buildingImport field is set.
     */
    boolean hasBuildingImport();
    /**
     * <code>.com.building.BuildingPkg building_import = 1;</code>
     * @return The buildingImport.
     */
    com.building.BuildingPkgOuterClass.BuildingPkg getBuildingImport();
    /**
     * <code>.com.building.BuildingPkg building_import = 1;</code>
     */
    com.building.BuildingPkgOuterClass.BuildingPkgOrBuilder getBuildingImportOrBuilder();

    /**
     * <code>.com.street.StreetPkg street_import = 2;</code>
     * @return Whether the streetImport field is set.
     */
    boolean hasStreetImport();
    /**
     * <code>.com.street.StreetPkg street_import = 2;</code>
     * @return The streetImport.
     */
    com.street.StreetPkgOuterClass.StreetPkg getStreetImport();
    /**
     * <code>.com.street.StreetPkg street_import = 2;</code>
     */
    com.street.StreetPkgOuterClass.StreetPkgOrBuilder getStreetImportOrBuilder();

    /**
     * <code>.com.city.CityPkg city_import = 3;</code>
     * @return Whether the cityImport field is set.
     */
    boolean hasCityImport();
    /**
     * <code>.com.city.CityPkg city_import = 3;</code>
     * @return The cityImport.
     */
    com.city.CityPkgOuterClass.CityPkg getCityImport();
    /**
     * <code>.com.city.CityPkg city_import = 3;</code>
     */
    com.city.CityPkgOuterClass.CityPkgOrBuilder getCityImportOrBuilder();
  }
  /**
   * Protobuf type {@code PkgTmpAddress}
   */
  public static final class PkgTmpAddress extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PkgTmpAddress)
      PkgTmpAddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PkgTmpAddress.newBuilder() to construct.
    private PkgTmpAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PkgTmpAddress() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PkgTmpAddress();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PkgTmpAddress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.building.BuildingPkgOuterClass.BuildingPkg.Builder subBuilder = null;
              if (buildingImport_ != null) {
                subBuilder = buildingImport_.toBuilder();
              }
              buildingImport_ = input.readMessage(com.building.BuildingPkgOuterClass.BuildingPkg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(buildingImport_);
                buildingImport_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.street.StreetPkgOuterClass.StreetPkg.Builder subBuilder = null;
              if (streetImport_ != null) {
                subBuilder = streetImport_.toBuilder();
              }
              streetImport_ = input.readMessage(com.street.StreetPkgOuterClass.StreetPkg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(streetImport_);
                streetImport_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.city.CityPkgOuterClass.CityPkg.Builder subBuilder = null;
              if (cityImport_ != null) {
                subBuilder = cityImport_.toBuilder();
              }
              cityImport_ = input.readMessage(com.city.CityPkgOuterClass.CityPkg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cityImport_);
                cityImport_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PkgTmpaddress.internal_static_PkgTmpAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PkgTmpaddress.internal_static_PkgTmpAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PkgTmpaddress.PkgTmpAddress.class, PkgTmpaddress.PkgTmpAddress.Builder.class);
    }

    public static final int BUILDING_IMPORT_FIELD_NUMBER = 1;
    private com.building.BuildingPkgOuterClass.BuildingPkg buildingImport_;
    /**
     * <code>.com.building.BuildingPkg building_import = 1;</code>
     * @return Whether the buildingImport field is set.
     */
    @java.lang.Override
    public boolean hasBuildingImport() {
      return buildingImport_ != null;
    }
    /**
     * <code>.com.building.BuildingPkg building_import = 1;</code>
     * @return The buildingImport.
     */
    @java.lang.Override
    public com.building.BuildingPkgOuterClass.BuildingPkg getBuildingImport() {
      return buildingImport_ == null ? com.building.BuildingPkgOuterClass.BuildingPkg.getDefaultInstance() : buildingImport_;
    }
    /**
     * <code>.com.building.BuildingPkg building_import = 1;</code>
     */
    @java.lang.Override
    public com.building.BuildingPkgOuterClass.BuildingPkgOrBuilder getBuildingImportOrBuilder() {
      return getBuildingImport();
    }

    public static final int STREET_IMPORT_FIELD_NUMBER = 2;
    private com.street.StreetPkgOuterClass.StreetPkg streetImport_;
    /**
     * <code>.com.street.StreetPkg street_import = 2;</code>
     * @return Whether the streetImport field is set.
     */
    @java.lang.Override
    public boolean hasStreetImport() {
      return streetImport_ != null;
    }
    /**
     * <code>.com.street.StreetPkg street_import = 2;</code>
     * @return The streetImport.
     */
    @java.lang.Override
    public com.street.StreetPkgOuterClass.StreetPkg getStreetImport() {
      return streetImport_ == null ? com.street.StreetPkgOuterClass.StreetPkg.getDefaultInstance() : streetImport_;
    }
    /**
     * <code>.com.street.StreetPkg street_import = 2;</code>
     */
    @java.lang.Override
    public com.street.StreetPkgOuterClass.StreetPkgOrBuilder getStreetImportOrBuilder() {
      return getStreetImport();
    }

    public static final int CITY_IMPORT_FIELD_NUMBER = 3;
    private com.city.CityPkgOuterClass.CityPkg cityImport_;
    /**
     * <code>.com.city.CityPkg city_import = 3;</code>
     * @return Whether the cityImport field is set.
     */
    @java.lang.Override
    public boolean hasCityImport() {
      return cityImport_ != null;
    }
    /**
     * <code>.com.city.CityPkg city_import = 3;</code>
     * @return The cityImport.
     */
    @java.lang.Override
    public com.city.CityPkgOuterClass.CityPkg getCityImport() {
      return cityImport_ == null ? com.city.CityPkgOuterClass.CityPkg.getDefaultInstance() : cityImport_;
    }
    /**
     * <code>.com.city.CityPkg city_import = 3;</code>
     */
    @java.lang.Override
    public com.city.CityPkgOuterClass.CityPkgOrBuilder getCityImportOrBuilder() {
      return getCityImport();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (buildingImport_ != null) {
        output.writeMessage(1, getBuildingImport());
      }
      if (streetImport_ != null) {
        output.writeMessage(2, getStreetImport());
      }
      if (cityImport_ != null) {
        output.writeMessage(3, getCityImport());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (buildingImport_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBuildingImport());
      }
      if (streetImport_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStreetImport());
      }
      if (cityImport_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCityImport());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PkgTmpaddress.PkgTmpAddress)) {
        return super.equals(obj);
      }
      PkgTmpaddress.PkgTmpAddress other = (PkgTmpaddress.PkgTmpAddress) obj;

      if (hasBuildingImport() != other.hasBuildingImport()) return false;
      if (hasBuildingImport()) {
        if (!getBuildingImport()
            .equals(other.getBuildingImport())) return false;
      }
      if (hasStreetImport() != other.hasStreetImport()) return false;
      if (hasStreetImport()) {
        if (!getStreetImport()
            .equals(other.getStreetImport())) return false;
      }
      if (hasCityImport() != other.hasCityImport()) return false;
      if (hasCityImport()) {
        if (!getCityImport()
            .equals(other.getCityImport())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuildingImport()) {
        hash = (37 * hash) + BUILDING_IMPORT_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingImport().hashCode();
      }
      if (hasStreetImport()) {
        hash = (37 * hash) + STREET_IMPORT_FIELD_NUMBER;
        hash = (53 * hash) + getStreetImport().hashCode();
      }
      if (hasCityImport()) {
        hash = (37 * hash) + CITY_IMPORT_FIELD_NUMBER;
        hash = (53 * hash) + getCityImport().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PkgTmpaddress.PkgTmpAddress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PkgTmpaddress.PkgTmpAddress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PkgTmpaddress.PkgTmpAddress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PkgTmpaddress.PkgTmpAddress prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PkgTmpAddress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PkgTmpAddress)
        PkgTmpaddress.PkgTmpAddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PkgTmpaddress.internal_static_PkgTmpAddress_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PkgTmpaddress.internal_static_PkgTmpAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PkgTmpaddress.PkgTmpAddress.class, PkgTmpaddress.PkgTmpAddress.Builder.class);
      }

      // Construct using PkgTmpaddress.PkgTmpAddress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (buildingImportBuilder_ == null) {
          buildingImport_ = null;
        } else {
          buildingImport_ = null;
          buildingImportBuilder_ = null;
        }
        if (streetImportBuilder_ == null) {
          streetImport_ = null;
        } else {
          streetImport_ = null;
          streetImportBuilder_ = null;
        }
        if (cityImportBuilder_ == null) {
          cityImport_ = null;
        } else {
          cityImport_ = null;
          cityImportBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PkgTmpaddress.internal_static_PkgTmpAddress_descriptor;
      }

      @java.lang.Override
      public PkgTmpaddress.PkgTmpAddress getDefaultInstanceForType() {
        return PkgTmpaddress.PkgTmpAddress.getDefaultInstance();
      }

      @java.lang.Override
      public PkgTmpaddress.PkgTmpAddress build() {
        PkgTmpaddress.PkgTmpAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PkgTmpaddress.PkgTmpAddress buildPartial() {
        PkgTmpaddress.PkgTmpAddress result = new PkgTmpaddress.PkgTmpAddress(this);
        if (buildingImportBuilder_ == null) {
          result.buildingImport_ = buildingImport_;
        } else {
          result.buildingImport_ = buildingImportBuilder_.build();
        }
        if (streetImportBuilder_ == null) {
          result.streetImport_ = streetImport_;
        } else {
          result.streetImport_ = streetImportBuilder_.build();
        }
        if (cityImportBuilder_ == null) {
          result.cityImport_ = cityImport_;
        } else {
          result.cityImport_ = cityImportBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PkgTmpaddress.PkgTmpAddress) {
          return mergeFrom((PkgTmpaddress.PkgTmpAddress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PkgTmpaddress.PkgTmpAddress other) {
        if (other == PkgTmpaddress.PkgTmpAddress.getDefaultInstance()) return this;
        if (other.hasBuildingImport()) {
          mergeBuildingImport(other.getBuildingImport());
        }
        if (other.hasStreetImport()) {
          mergeStreetImport(other.getStreetImport());
        }
        if (other.hasCityImport()) {
          mergeCityImport(other.getCityImport());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PkgTmpaddress.PkgTmpAddress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PkgTmpaddress.PkgTmpAddress) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.building.BuildingPkgOuterClass.BuildingPkg buildingImport_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.building.BuildingPkgOuterClass.BuildingPkg, com.building.BuildingPkgOuterClass.BuildingPkg.Builder, com.building.BuildingPkgOuterClass.BuildingPkgOrBuilder> buildingImportBuilder_;
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       * @return Whether the buildingImport field is set.
       */
      public boolean hasBuildingImport() {
        return buildingImportBuilder_ != null || buildingImport_ != null;
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       * @return The buildingImport.
       */
      public com.building.BuildingPkgOuterClass.BuildingPkg getBuildingImport() {
        if (buildingImportBuilder_ == null) {
          return buildingImport_ == null ? com.building.BuildingPkgOuterClass.BuildingPkg.getDefaultInstance() : buildingImport_;
        } else {
          return buildingImportBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      public Builder setBuildingImport(com.building.BuildingPkgOuterClass.BuildingPkg value) {
        if (buildingImportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buildingImport_ = value;
          onChanged();
        } else {
          buildingImportBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      public Builder setBuildingImport(
          com.building.BuildingPkgOuterClass.BuildingPkg.Builder builderForValue) {
        if (buildingImportBuilder_ == null) {
          buildingImport_ = builderForValue.build();
          onChanged();
        } else {
          buildingImportBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      public Builder mergeBuildingImport(com.building.BuildingPkgOuterClass.BuildingPkg value) {
        if (buildingImportBuilder_ == null) {
          if (buildingImport_ != null) {
            buildingImport_ =
              com.building.BuildingPkgOuterClass.BuildingPkg.newBuilder(buildingImport_).mergeFrom(value).buildPartial();
          } else {
            buildingImport_ = value;
          }
          onChanged();
        } else {
          buildingImportBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      public Builder clearBuildingImport() {
        if (buildingImportBuilder_ == null) {
          buildingImport_ = null;
          onChanged();
        } else {
          buildingImport_ = null;
          buildingImportBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      public com.building.BuildingPkgOuterClass.BuildingPkg.Builder getBuildingImportBuilder() {
        
        onChanged();
        return getBuildingImportFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      public com.building.BuildingPkgOuterClass.BuildingPkgOrBuilder getBuildingImportOrBuilder() {
        if (buildingImportBuilder_ != null) {
          return buildingImportBuilder_.getMessageOrBuilder();
        } else {
          return buildingImport_ == null ?
              com.building.BuildingPkgOuterClass.BuildingPkg.getDefaultInstance() : buildingImport_;
        }
      }
      /**
       * <code>.com.building.BuildingPkg building_import = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.building.BuildingPkgOuterClass.BuildingPkg, com.building.BuildingPkgOuterClass.BuildingPkg.Builder, com.building.BuildingPkgOuterClass.BuildingPkgOrBuilder> 
          getBuildingImportFieldBuilder() {
        if (buildingImportBuilder_ == null) {
          buildingImportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.building.BuildingPkgOuterClass.BuildingPkg, com.building.BuildingPkgOuterClass.BuildingPkg.Builder, com.building.BuildingPkgOuterClass.BuildingPkgOrBuilder>(
                  getBuildingImport(),
                  getParentForChildren(),
                  isClean());
          buildingImport_ = null;
        }
        return buildingImportBuilder_;
      }

      private com.street.StreetPkgOuterClass.StreetPkg streetImport_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.street.StreetPkgOuterClass.StreetPkg, com.street.StreetPkgOuterClass.StreetPkg.Builder, com.street.StreetPkgOuterClass.StreetPkgOrBuilder> streetImportBuilder_;
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       * @return Whether the streetImport field is set.
       */
      public boolean hasStreetImport() {
        return streetImportBuilder_ != null || streetImport_ != null;
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       * @return The streetImport.
       */
      public com.street.StreetPkgOuterClass.StreetPkg getStreetImport() {
        if (streetImportBuilder_ == null) {
          return streetImport_ == null ? com.street.StreetPkgOuterClass.StreetPkg.getDefaultInstance() : streetImport_;
        } else {
          return streetImportBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      public Builder setStreetImport(com.street.StreetPkgOuterClass.StreetPkg value) {
        if (streetImportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          streetImport_ = value;
          onChanged();
        } else {
          streetImportBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      public Builder setStreetImport(
          com.street.StreetPkgOuterClass.StreetPkg.Builder builderForValue) {
        if (streetImportBuilder_ == null) {
          streetImport_ = builderForValue.build();
          onChanged();
        } else {
          streetImportBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      public Builder mergeStreetImport(com.street.StreetPkgOuterClass.StreetPkg value) {
        if (streetImportBuilder_ == null) {
          if (streetImport_ != null) {
            streetImport_ =
              com.street.StreetPkgOuterClass.StreetPkg.newBuilder(streetImport_).mergeFrom(value).buildPartial();
          } else {
            streetImport_ = value;
          }
          onChanged();
        } else {
          streetImportBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      public Builder clearStreetImport() {
        if (streetImportBuilder_ == null) {
          streetImport_ = null;
          onChanged();
        } else {
          streetImport_ = null;
          streetImportBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      public com.street.StreetPkgOuterClass.StreetPkg.Builder getStreetImportBuilder() {
        
        onChanged();
        return getStreetImportFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      public com.street.StreetPkgOuterClass.StreetPkgOrBuilder getStreetImportOrBuilder() {
        if (streetImportBuilder_ != null) {
          return streetImportBuilder_.getMessageOrBuilder();
        } else {
          return streetImport_ == null ?
              com.street.StreetPkgOuterClass.StreetPkg.getDefaultInstance() : streetImport_;
        }
      }
      /**
       * <code>.com.street.StreetPkg street_import = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.street.StreetPkgOuterClass.StreetPkg, com.street.StreetPkgOuterClass.StreetPkg.Builder, com.street.StreetPkgOuterClass.StreetPkgOrBuilder> 
          getStreetImportFieldBuilder() {
        if (streetImportBuilder_ == null) {
          streetImportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.street.StreetPkgOuterClass.StreetPkg, com.street.StreetPkgOuterClass.StreetPkg.Builder, com.street.StreetPkgOuterClass.StreetPkgOrBuilder>(
                  getStreetImport(),
                  getParentForChildren(),
                  isClean());
          streetImport_ = null;
        }
        return streetImportBuilder_;
      }

      private com.city.CityPkgOuterClass.CityPkg cityImport_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.city.CityPkgOuterClass.CityPkg, com.city.CityPkgOuterClass.CityPkg.Builder, com.city.CityPkgOuterClass.CityPkgOrBuilder> cityImportBuilder_;
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       * @return Whether the cityImport field is set.
       */
      public boolean hasCityImport() {
        return cityImportBuilder_ != null || cityImport_ != null;
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       * @return The cityImport.
       */
      public com.city.CityPkgOuterClass.CityPkg getCityImport() {
        if (cityImportBuilder_ == null) {
          return cityImport_ == null ? com.city.CityPkgOuterClass.CityPkg.getDefaultInstance() : cityImport_;
        } else {
          return cityImportBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      public Builder setCityImport(com.city.CityPkgOuterClass.CityPkg value) {
        if (cityImportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cityImport_ = value;
          onChanged();
        } else {
          cityImportBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      public Builder setCityImport(
          com.city.CityPkgOuterClass.CityPkg.Builder builderForValue) {
        if (cityImportBuilder_ == null) {
          cityImport_ = builderForValue.build();
          onChanged();
        } else {
          cityImportBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      public Builder mergeCityImport(com.city.CityPkgOuterClass.CityPkg value) {
        if (cityImportBuilder_ == null) {
          if (cityImport_ != null) {
            cityImport_ =
              com.city.CityPkgOuterClass.CityPkg.newBuilder(cityImport_).mergeFrom(value).buildPartial();
          } else {
            cityImport_ = value;
          }
          onChanged();
        } else {
          cityImportBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      public Builder clearCityImport() {
        if (cityImportBuilder_ == null) {
          cityImport_ = null;
          onChanged();
        } else {
          cityImport_ = null;
          cityImportBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      public com.city.CityPkgOuterClass.CityPkg.Builder getCityImportBuilder() {
        
        onChanged();
        return getCityImportFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      public com.city.CityPkgOuterClass.CityPkgOrBuilder getCityImportOrBuilder() {
        if (cityImportBuilder_ != null) {
          return cityImportBuilder_.getMessageOrBuilder();
        } else {
          return cityImport_ == null ?
              com.city.CityPkgOuterClass.CityPkg.getDefaultInstance() : cityImport_;
        }
      }
      /**
       * <code>.com.city.CityPkg city_import = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.city.CityPkgOuterClass.CityPkg, com.city.CityPkgOuterClass.CityPkg.Builder, com.city.CityPkgOuterClass.CityPkgOrBuilder> 
          getCityImportFieldBuilder() {
        if (cityImportBuilder_ == null) {
          cityImportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.city.CityPkgOuterClass.CityPkg, com.city.CityPkgOuterClass.CityPkg.Builder, com.city.CityPkgOuterClass.CityPkgOrBuilder>(
                  getCityImport(),
                  getParentForChildren(),
                  isClean());
          cityImport_ = null;
        }
        return cityImportBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PkgTmpAddress)
    }

    // @@protoc_insertion_point(class_scope:PkgTmpAddress)
    private static final PkgTmpaddress.PkgTmpAddress DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PkgTmpaddress.PkgTmpAddress();
    }

    public static PkgTmpaddress.PkgTmpAddress getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PkgTmpAddress>
        PARSER = new com.google.protobuf.AbstractParser<PkgTmpAddress>() {
      @java.lang.Override
      public PkgTmpAddress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PkgTmpAddress(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PkgTmpAddress> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PkgTmpAddress> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PkgTmpaddress.PkgTmpAddress getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PkgTmpAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PkgTmpAddress_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024pkg-tmpaddress.proto\032\022building-pkg.pro" +
      "to\032\020street-pkg.proto\032\016city-pkg.proto\"\231\001\n" +
      "\rPkgTmpAddress\0222\n\017building_import\030\001 \001(\0132" +
      "\031.com.building.BuildingPkg\022,\n\rstreet_imp" +
      "ort\030\002 \001(\0132\025.com.street.StreetPkg\022&\n\013city" +
      "_import\030\003 \001(\0132\021.com.city.CityPkgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.building.BuildingPkgOuterClass.getDescriptor(),
          com.street.StreetPkgOuterClass.getDescriptor(),
          com.city.CityPkgOuterClass.getDescriptor(),
        });
    internal_static_PkgTmpAddress_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PkgTmpAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PkgTmpAddress_descriptor,
        new java.lang.String[] { "BuildingImport", "StreetImport", "CityImport", });
    com.building.BuildingPkgOuterClass.getDescriptor();
    com.street.StreetPkgOuterClass.getDescriptor();
    com.city.CityPkgOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
