# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: street-pkg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import city_pkg_pb2 as city__pkg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='street-pkg.proto',
  package='com.street',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10street-pkg.proto\x12\ncom.street\x1a\x0e\x63ity-pkg.proto\"I\n\tStreetPkg\x12\x13\n\x0bstreet_name\x18\x01 \x01(\t\x12\'\n\x0c\x63ity_details\x18\x02 \x01(\x0b\x32\x11.com.city.CityPkgb\x06proto3'
  ,
  dependencies=[city__pkg__pb2.DESCRIPTOR,])




_STREETPKG = _descriptor.Descriptor(
  name='StreetPkg',
  full_name='com.street.StreetPkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='street_name', full_name='com.street.StreetPkg.street_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city_details', full_name='com.street.StreetPkg.city_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=121,
)

_STREETPKG.fields_by_name['city_details'].message_type = city__pkg__pb2._CITYPKG
DESCRIPTOR.message_types_by_name['StreetPkg'] = _STREETPKG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreetPkg = _reflection.GeneratedProtocolMessageType('StreetPkg', (_message.Message,), {
  'DESCRIPTOR' : _STREETPKG,
  '__module__' : 'street_pkg_pb2'
  # @@protoc_insertion_point(class_scope:com.street.StreetPkg)
  })
_sym_db.RegisterMessage(StreetPkg)


# @@protoc_insertion_point(module_scope)
