// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: importedtmpaddress.proto

public final class Importedtmpaddress {
  private Importedtmpaddress() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImportedTmpAddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImportedTmpAddress)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BuildingImport building_import = 1;</code>
     * @return Whether the buildingImport field is set.
     */
    boolean hasBuildingImport();
    /**
     * <code>.BuildingImport building_import = 1;</code>
     * @return The buildingImport.
     */
    Building.BuildingImport getBuildingImport();
    /**
     * <code>.BuildingImport building_import = 1;</code>
     */
    Building.BuildingImportOrBuilder getBuildingImportOrBuilder();

    /**
     * <code>.StreetImport street_import = 2;</code>
     * @return Whether the streetImport field is set.
     */
    boolean hasStreetImport();
    /**
     * <code>.StreetImport street_import = 2;</code>
     * @return The streetImport.
     */
    Street.StreetImport getStreetImport();
    /**
     * <code>.StreetImport street_import = 2;</code>
     */
    Street.StreetImportOrBuilder getStreetImportOrBuilder();

    /**
     * <code>.CityImport city_import = 3;</code>
     * @return Whether the cityImport field is set.
     */
    boolean hasCityImport();
    /**
     * <code>.CityImport city_import = 3;</code>
     * @return The cityImport.
     */
    City.CityImport getCityImport();
    /**
     * <code>.CityImport city_import = 3;</code>
     */
    City.CityImportOrBuilder getCityImportOrBuilder();
  }
  /**
   * Protobuf type {@code ImportedTmpAddress}
   */
  public static final class ImportedTmpAddress extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImportedTmpAddress)
      ImportedTmpAddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImportedTmpAddress.newBuilder() to construct.
    private ImportedTmpAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImportedTmpAddress() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImportedTmpAddress();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImportedTmpAddress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Building.BuildingImport.Builder subBuilder = null;
              if (buildingImport_ != null) {
                subBuilder = buildingImport_.toBuilder();
              }
              buildingImport_ = input.readMessage(Building.BuildingImport.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(buildingImport_);
                buildingImport_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              Street.StreetImport.Builder subBuilder = null;
              if (streetImport_ != null) {
                subBuilder = streetImport_.toBuilder();
              }
              streetImport_ = input.readMessage(Street.StreetImport.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(streetImport_);
                streetImport_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              City.CityImport.Builder subBuilder = null;
              if (cityImport_ != null) {
                subBuilder = cityImport_.toBuilder();
              }
              cityImport_ = input.readMessage(City.CityImport.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cityImport_);
                cityImport_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Importedtmpaddress.internal_static_ImportedTmpAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Importedtmpaddress.internal_static_ImportedTmpAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Importedtmpaddress.ImportedTmpAddress.class, Importedtmpaddress.ImportedTmpAddress.Builder.class);
    }

    public static final int BUILDING_IMPORT_FIELD_NUMBER = 1;
    private Building.BuildingImport buildingImport_;
    /**
     * <code>.BuildingImport building_import = 1;</code>
     * @return Whether the buildingImport field is set.
     */
    @java.lang.Override
    public boolean hasBuildingImport() {
      return buildingImport_ != null;
    }
    /**
     * <code>.BuildingImport building_import = 1;</code>
     * @return The buildingImport.
     */
    @java.lang.Override
    public Building.BuildingImport getBuildingImport() {
      return buildingImport_ == null ? Building.BuildingImport.getDefaultInstance() : buildingImport_;
    }
    /**
     * <code>.BuildingImport building_import = 1;</code>
     */
    @java.lang.Override
    public Building.BuildingImportOrBuilder getBuildingImportOrBuilder() {
      return getBuildingImport();
    }

    public static final int STREET_IMPORT_FIELD_NUMBER = 2;
    private Street.StreetImport streetImport_;
    /**
     * <code>.StreetImport street_import = 2;</code>
     * @return Whether the streetImport field is set.
     */
    @java.lang.Override
    public boolean hasStreetImport() {
      return streetImport_ != null;
    }
    /**
     * <code>.StreetImport street_import = 2;</code>
     * @return The streetImport.
     */
    @java.lang.Override
    public Street.StreetImport getStreetImport() {
      return streetImport_ == null ? Street.StreetImport.getDefaultInstance() : streetImport_;
    }
    /**
     * <code>.StreetImport street_import = 2;</code>
     */
    @java.lang.Override
    public Street.StreetImportOrBuilder getStreetImportOrBuilder() {
      return getStreetImport();
    }

    public static final int CITY_IMPORT_FIELD_NUMBER = 3;
    private City.CityImport cityImport_;
    /**
     * <code>.CityImport city_import = 3;</code>
     * @return Whether the cityImport field is set.
     */
    @java.lang.Override
    public boolean hasCityImport() {
      return cityImport_ != null;
    }
    /**
     * <code>.CityImport city_import = 3;</code>
     * @return The cityImport.
     */
    @java.lang.Override
    public City.CityImport getCityImport() {
      return cityImport_ == null ? City.CityImport.getDefaultInstance() : cityImport_;
    }
    /**
     * <code>.CityImport city_import = 3;</code>
     */
    @java.lang.Override
    public City.CityImportOrBuilder getCityImportOrBuilder() {
      return getCityImport();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (buildingImport_ != null) {
        output.writeMessage(1, getBuildingImport());
      }
      if (streetImport_ != null) {
        output.writeMessage(2, getStreetImport());
      }
      if (cityImport_ != null) {
        output.writeMessage(3, getCityImport());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (buildingImport_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBuildingImport());
      }
      if (streetImport_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStreetImport());
      }
      if (cityImport_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCityImport());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Importedtmpaddress.ImportedTmpAddress)) {
        return super.equals(obj);
      }
      Importedtmpaddress.ImportedTmpAddress other = (Importedtmpaddress.ImportedTmpAddress) obj;

      if (hasBuildingImport() != other.hasBuildingImport()) return false;
      if (hasBuildingImport()) {
        if (!getBuildingImport()
            .equals(other.getBuildingImport())) return false;
      }
      if (hasStreetImport() != other.hasStreetImport()) return false;
      if (hasStreetImport()) {
        if (!getStreetImport()
            .equals(other.getStreetImport())) return false;
      }
      if (hasCityImport() != other.hasCityImport()) return false;
      if (hasCityImport()) {
        if (!getCityImport()
            .equals(other.getCityImport())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuildingImport()) {
        hash = (37 * hash) + BUILDING_IMPORT_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingImport().hashCode();
      }
      if (hasStreetImport()) {
        hash = (37 * hash) + STREET_IMPORT_FIELD_NUMBER;
        hash = (53 * hash) + getStreetImport().hashCode();
      }
      if (hasCityImport()) {
        hash = (37 * hash) + CITY_IMPORT_FIELD_NUMBER;
        hash = (53 * hash) + getCityImport().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Importedtmpaddress.ImportedTmpAddress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Importedtmpaddress.ImportedTmpAddress prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImportedTmpAddress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImportedTmpAddress)
        Importedtmpaddress.ImportedTmpAddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Importedtmpaddress.internal_static_ImportedTmpAddress_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Importedtmpaddress.internal_static_ImportedTmpAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Importedtmpaddress.ImportedTmpAddress.class, Importedtmpaddress.ImportedTmpAddress.Builder.class);
      }

      // Construct using Importedtmpaddress.ImportedTmpAddress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (buildingImportBuilder_ == null) {
          buildingImport_ = null;
        } else {
          buildingImport_ = null;
          buildingImportBuilder_ = null;
        }
        if (streetImportBuilder_ == null) {
          streetImport_ = null;
        } else {
          streetImport_ = null;
          streetImportBuilder_ = null;
        }
        if (cityImportBuilder_ == null) {
          cityImport_ = null;
        } else {
          cityImport_ = null;
          cityImportBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Importedtmpaddress.internal_static_ImportedTmpAddress_descriptor;
      }

      @java.lang.Override
      public Importedtmpaddress.ImportedTmpAddress getDefaultInstanceForType() {
        return Importedtmpaddress.ImportedTmpAddress.getDefaultInstance();
      }

      @java.lang.Override
      public Importedtmpaddress.ImportedTmpAddress build() {
        Importedtmpaddress.ImportedTmpAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Importedtmpaddress.ImportedTmpAddress buildPartial() {
        Importedtmpaddress.ImportedTmpAddress result = new Importedtmpaddress.ImportedTmpAddress(this);
        if (buildingImportBuilder_ == null) {
          result.buildingImport_ = buildingImport_;
        } else {
          result.buildingImport_ = buildingImportBuilder_.build();
        }
        if (streetImportBuilder_ == null) {
          result.streetImport_ = streetImport_;
        } else {
          result.streetImport_ = streetImportBuilder_.build();
        }
        if (cityImportBuilder_ == null) {
          result.cityImport_ = cityImport_;
        } else {
          result.cityImport_ = cityImportBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Importedtmpaddress.ImportedTmpAddress) {
          return mergeFrom((Importedtmpaddress.ImportedTmpAddress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Importedtmpaddress.ImportedTmpAddress other) {
        if (other == Importedtmpaddress.ImportedTmpAddress.getDefaultInstance()) return this;
        if (other.hasBuildingImport()) {
          mergeBuildingImport(other.getBuildingImport());
        }
        if (other.hasStreetImport()) {
          mergeStreetImport(other.getStreetImport());
        }
        if (other.hasCityImport()) {
          mergeCityImport(other.getCityImport());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Importedtmpaddress.ImportedTmpAddress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Importedtmpaddress.ImportedTmpAddress) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Building.BuildingImport buildingImport_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Building.BuildingImport, Building.BuildingImport.Builder, Building.BuildingImportOrBuilder> buildingImportBuilder_;
      /**
       * <code>.BuildingImport building_import = 1;</code>
       * @return Whether the buildingImport field is set.
       */
      public boolean hasBuildingImport() {
        return buildingImportBuilder_ != null || buildingImport_ != null;
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       * @return The buildingImport.
       */
      public Building.BuildingImport getBuildingImport() {
        if (buildingImportBuilder_ == null) {
          return buildingImport_ == null ? Building.BuildingImport.getDefaultInstance() : buildingImport_;
        } else {
          return buildingImportBuilder_.getMessage();
        }
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      public Builder setBuildingImport(Building.BuildingImport value) {
        if (buildingImportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buildingImport_ = value;
          onChanged();
        } else {
          buildingImportBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      public Builder setBuildingImport(
          Building.BuildingImport.Builder builderForValue) {
        if (buildingImportBuilder_ == null) {
          buildingImport_ = builderForValue.build();
          onChanged();
        } else {
          buildingImportBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      public Builder mergeBuildingImport(Building.BuildingImport value) {
        if (buildingImportBuilder_ == null) {
          if (buildingImport_ != null) {
            buildingImport_ =
              Building.BuildingImport.newBuilder(buildingImport_).mergeFrom(value).buildPartial();
          } else {
            buildingImport_ = value;
          }
          onChanged();
        } else {
          buildingImportBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      public Builder clearBuildingImport() {
        if (buildingImportBuilder_ == null) {
          buildingImport_ = null;
          onChanged();
        } else {
          buildingImport_ = null;
          buildingImportBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      public Building.BuildingImport.Builder getBuildingImportBuilder() {
        
        onChanged();
        return getBuildingImportFieldBuilder().getBuilder();
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      public Building.BuildingImportOrBuilder getBuildingImportOrBuilder() {
        if (buildingImportBuilder_ != null) {
          return buildingImportBuilder_.getMessageOrBuilder();
        } else {
          return buildingImport_ == null ?
              Building.BuildingImport.getDefaultInstance() : buildingImport_;
        }
      }
      /**
       * <code>.BuildingImport building_import = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Building.BuildingImport, Building.BuildingImport.Builder, Building.BuildingImportOrBuilder> 
          getBuildingImportFieldBuilder() {
        if (buildingImportBuilder_ == null) {
          buildingImportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Building.BuildingImport, Building.BuildingImport.Builder, Building.BuildingImportOrBuilder>(
                  getBuildingImport(),
                  getParentForChildren(),
                  isClean());
          buildingImport_ = null;
        }
        return buildingImportBuilder_;
      }

      private Street.StreetImport streetImport_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Street.StreetImport, Street.StreetImport.Builder, Street.StreetImportOrBuilder> streetImportBuilder_;
      /**
       * <code>.StreetImport street_import = 2;</code>
       * @return Whether the streetImport field is set.
       */
      public boolean hasStreetImport() {
        return streetImportBuilder_ != null || streetImport_ != null;
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       * @return The streetImport.
       */
      public Street.StreetImport getStreetImport() {
        if (streetImportBuilder_ == null) {
          return streetImport_ == null ? Street.StreetImport.getDefaultInstance() : streetImport_;
        } else {
          return streetImportBuilder_.getMessage();
        }
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      public Builder setStreetImport(Street.StreetImport value) {
        if (streetImportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          streetImport_ = value;
          onChanged();
        } else {
          streetImportBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      public Builder setStreetImport(
          Street.StreetImport.Builder builderForValue) {
        if (streetImportBuilder_ == null) {
          streetImport_ = builderForValue.build();
          onChanged();
        } else {
          streetImportBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      public Builder mergeStreetImport(Street.StreetImport value) {
        if (streetImportBuilder_ == null) {
          if (streetImport_ != null) {
            streetImport_ =
              Street.StreetImport.newBuilder(streetImport_).mergeFrom(value).buildPartial();
          } else {
            streetImport_ = value;
          }
          onChanged();
        } else {
          streetImportBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      public Builder clearStreetImport() {
        if (streetImportBuilder_ == null) {
          streetImport_ = null;
          onChanged();
        } else {
          streetImport_ = null;
          streetImportBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      public Street.StreetImport.Builder getStreetImportBuilder() {
        
        onChanged();
        return getStreetImportFieldBuilder().getBuilder();
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      public Street.StreetImportOrBuilder getStreetImportOrBuilder() {
        if (streetImportBuilder_ != null) {
          return streetImportBuilder_.getMessageOrBuilder();
        } else {
          return streetImport_ == null ?
              Street.StreetImport.getDefaultInstance() : streetImport_;
        }
      }
      /**
       * <code>.StreetImport street_import = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Street.StreetImport, Street.StreetImport.Builder, Street.StreetImportOrBuilder> 
          getStreetImportFieldBuilder() {
        if (streetImportBuilder_ == null) {
          streetImportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Street.StreetImport, Street.StreetImport.Builder, Street.StreetImportOrBuilder>(
                  getStreetImport(),
                  getParentForChildren(),
                  isClean());
          streetImport_ = null;
        }
        return streetImportBuilder_;
      }

      private City.CityImport cityImport_;
      private com.google.protobuf.SingleFieldBuilderV3<
          City.CityImport, City.CityImport.Builder, City.CityImportOrBuilder> cityImportBuilder_;
      /**
       * <code>.CityImport city_import = 3;</code>
       * @return Whether the cityImport field is set.
       */
      public boolean hasCityImport() {
        return cityImportBuilder_ != null || cityImport_ != null;
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       * @return The cityImport.
       */
      public City.CityImport getCityImport() {
        if (cityImportBuilder_ == null) {
          return cityImport_ == null ? City.CityImport.getDefaultInstance() : cityImport_;
        } else {
          return cityImportBuilder_.getMessage();
        }
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      public Builder setCityImport(City.CityImport value) {
        if (cityImportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cityImport_ = value;
          onChanged();
        } else {
          cityImportBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      public Builder setCityImport(
          City.CityImport.Builder builderForValue) {
        if (cityImportBuilder_ == null) {
          cityImport_ = builderForValue.build();
          onChanged();
        } else {
          cityImportBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      public Builder mergeCityImport(City.CityImport value) {
        if (cityImportBuilder_ == null) {
          if (cityImport_ != null) {
            cityImport_ =
              City.CityImport.newBuilder(cityImport_).mergeFrom(value).buildPartial();
          } else {
            cityImport_ = value;
          }
          onChanged();
        } else {
          cityImportBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      public Builder clearCityImport() {
        if (cityImportBuilder_ == null) {
          cityImport_ = null;
          onChanged();
        } else {
          cityImport_ = null;
          cityImportBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      public City.CityImport.Builder getCityImportBuilder() {
        
        onChanged();
        return getCityImportFieldBuilder().getBuilder();
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      public City.CityImportOrBuilder getCityImportOrBuilder() {
        if (cityImportBuilder_ != null) {
          return cityImportBuilder_.getMessageOrBuilder();
        } else {
          return cityImport_ == null ?
              City.CityImport.getDefaultInstance() : cityImport_;
        }
      }
      /**
       * <code>.CityImport city_import = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          City.CityImport, City.CityImport.Builder, City.CityImportOrBuilder> 
          getCityImportFieldBuilder() {
        if (cityImportBuilder_ == null) {
          cityImportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              City.CityImport, City.CityImport.Builder, City.CityImportOrBuilder>(
                  getCityImport(),
                  getParentForChildren(),
                  isClean());
          cityImport_ = null;
        }
        return cityImportBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImportedTmpAddress)
    }

    // @@protoc_insertion_point(class_scope:ImportedTmpAddress)
    private static final Importedtmpaddress.ImportedTmpAddress DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Importedtmpaddress.ImportedTmpAddress();
    }

    public static Importedtmpaddress.ImportedTmpAddress getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImportedTmpAddress>
        PARSER = new com.google.protobuf.AbstractParser<ImportedTmpAddress>() {
      @java.lang.Override
      public ImportedTmpAddress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImportedTmpAddress(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImportedTmpAddress> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImportedTmpAddress> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Importedtmpaddress.ImportedTmpAddress getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImportedTmpAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImportedTmpAddress_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030importedtmpaddress.proto\032\016building.pro" +
      "to\032\014street.proto\032\ncity.proto\"\206\001\n\022Importe" +
      "dTmpAddress\022(\n\017building_import\030\001 \001(\0132\017.B" +
      "uildingImport\022$\n\rstreet_import\030\002 \001(\0132\r.S" +
      "treetImport\022 \n\013city_import\030\003 \001(\0132\013.CityI" +
      "mportb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Building.getDescriptor(),
          Street.getDescriptor(),
          City.getDescriptor(),
        });
    internal_static_ImportedTmpAddress_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImportedTmpAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImportedTmpAddress_descriptor,
        new java.lang.String[] { "BuildingImport", "StreetImport", "CityImport", });
    Building.getDescriptor();
    Street.getDescriptor();
    City.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
