// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: street.proto

public final class Street {
  private Street() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreetImportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreetImport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string street_name = 1;</code>
     * @return The streetName.
     */
    java.lang.String getStreetName();
    /**
     * <code>string street_name = 1;</code>
     * @return The bytes for streetName.
     */
    com.google.protobuf.ByteString
        getStreetNameBytes();

    /**
     * <code>.CityImport city_details = 2;</code>
     * @return Whether the cityDetails field is set.
     */
    boolean hasCityDetails();
    /**
     * <code>.CityImport city_details = 2;</code>
     * @return The cityDetails.
     */
    City.CityImport getCityDetails();
    /**
     * <code>.CityImport city_details = 2;</code>
     */
    City.CityImportOrBuilder getCityDetailsOrBuilder();
  }
  /**
   * Protobuf type {@code StreetImport}
   */
  public static final class StreetImport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StreetImport)
      StreetImportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreetImport.newBuilder() to construct.
    private StreetImport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreetImport() {
      streetName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreetImport();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreetImport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              streetName_ = s;
              break;
            }
            case 18: {
              City.CityImport.Builder subBuilder = null;
              if (cityDetails_ != null) {
                subBuilder = cityDetails_.toBuilder();
              }
              cityDetails_ = input.readMessage(City.CityImport.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cityDetails_);
                cityDetails_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Street.internal_static_StreetImport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Street.internal_static_StreetImport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Street.StreetImport.class, Street.StreetImport.Builder.class);
    }

    public static final int STREET_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object streetName_;
    /**
     * <code>string street_name = 1;</code>
     * @return The streetName.
     */
    @java.lang.Override
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      }
    }
    /**
     * <code>string street_name = 1;</code>
     * @return The bytes for streetName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_DETAILS_FIELD_NUMBER = 2;
    private City.CityImport cityDetails_;
    /**
     * <code>.CityImport city_details = 2;</code>
     * @return Whether the cityDetails field is set.
     */
    @java.lang.Override
    public boolean hasCityDetails() {
      return cityDetails_ != null;
    }
    /**
     * <code>.CityImport city_details = 2;</code>
     * @return The cityDetails.
     */
    @java.lang.Override
    public City.CityImport getCityDetails() {
      return cityDetails_ == null ? City.CityImport.getDefaultInstance() : cityDetails_;
    }
    /**
     * <code>.CityImport city_details = 2;</code>
     */
    @java.lang.Override
    public City.CityImportOrBuilder getCityDetailsOrBuilder() {
      return getCityDetails();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStreetNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streetName_);
      }
      if (cityDetails_ != null) {
        output.writeMessage(2, getCityDetails());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStreetNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streetName_);
      }
      if (cityDetails_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCityDetails());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Street.StreetImport)) {
        return super.equals(obj);
      }
      Street.StreetImport other = (Street.StreetImport) obj;

      if (!getStreetName()
          .equals(other.getStreetName())) return false;
      if (hasCityDetails() != other.hasCityDetails()) return false;
      if (hasCityDetails()) {
        if (!getCityDetails()
            .equals(other.getCityDetails())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREET_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getStreetName().hashCode();
      if (hasCityDetails()) {
        hash = (37 * hash) + CITY_DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getCityDetails().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Street.StreetImport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Street.StreetImport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Street.StreetImport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Street.StreetImport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Street.StreetImport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Street.StreetImport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Street.StreetImport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Street.StreetImport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Street.StreetImport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Street.StreetImport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Street.StreetImport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Street.StreetImport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Street.StreetImport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreetImport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreetImport)
        Street.StreetImportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Street.internal_static_StreetImport_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Street.internal_static_StreetImport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Street.StreetImport.class, Street.StreetImport.Builder.class);
      }

      // Construct using Street.StreetImport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streetName_ = "";

        if (cityDetailsBuilder_ == null) {
          cityDetails_ = null;
        } else {
          cityDetails_ = null;
          cityDetailsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Street.internal_static_StreetImport_descriptor;
      }

      @java.lang.Override
      public Street.StreetImport getDefaultInstanceForType() {
        return Street.StreetImport.getDefaultInstance();
      }

      @java.lang.Override
      public Street.StreetImport build() {
        Street.StreetImport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Street.StreetImport buildPartial() {
        Street.StreetImport result = new Street.StreetImport(this);
        result.streetName_ = streetName_;
        if (cityDetailsBuilder_ == null) {
          result.cityDetails_ = cityDetails_;
        } else {
          result.cityDetails_ = cityDetailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Street.StreetImport) {
          return mergeFrom((Street.StreetImport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Street.StreetImport other) {
        if (other == Street.StreetImport.getDefaultInstance()) return this;
        if (!other.getStreetName().isEmpty()) {
          streetName_ = other.streetName_;
          onChanged();
        }
        if (other.hasCityDetails()) {
          mergeCityDetails(other.getCityDetails());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Street.StreetImport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Street.StreetImport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object streetName_ = "";
      /**
       * <code>string street_name = 1;</code>
       * @return The streetName.
       */
      public java.lang.String getStreetName() {
        java.lang.Object ref = streetName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street_name = 1;</code>
       * @return The bytes for streetName.
       */
      public com.google.protobuf.ByteString
          getStreetNameBytes() {
        java.lang.Object ref = streetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street_name = 1;</code>
       * @param value The streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string street_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreetName() {
        
        streetName_ = getDefaultInstance().getStreetName();
        onChanged();
        return this;
      }
      /**
       * <code>string street_name = 1;</code>
       * @param value The bytes for streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streetName_ = value;
        onChanged();
        return this;
      }

      private City.CityImport cityDetails_;
      private com.google.protobuf.SingleFieldBuilderV3<
          City.CityImport, City.CityImport.Builder, City.CityImportOrBuilder> cityDetailsBuilder_;
      /**
       * <code>.CityImport city_details = 2;</code>
       * @return Whether the cityDetails field is set.
       */
      public boolean hasCityDetails() {
        return cityDetailsBuilder_ != null || cityDetails_ != null;
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       * @return The cityDetails.
       */
      public City.CityImport getCityDetails() {
        if (cityDetailsBuilder_ == null) {
          return cityDetails_ == null ? City.CityImport.getDefaultInstance() : cityDetails_;
        } else {
          return cityDetailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      public Builder setCityDetails(City.CityImport value) {
        if (cityDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cityDetails_ = value;
          onChanged();
        } else {
          cityDetailsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      public Builder setCityDetails(
          City.CityImport.Builder builderForValue) {
        if (cityDetailsBuilder_ == null) {
          cityDetails_ = builderForValue.build();
          onChanged();
        } else {
          cityDetailsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      public Builder mergeCityDetails(City.CityImport value) {
        if (cityDetailsBuilder_ == null) {
          if (cityDetails_ != null) {
            cityDetails_ =
              City.CityImport.newBuilder(cityDetails_).mergeFrom(value).buildPartial();
          } else {
            cityDetails_ = value;
          }
          onChanged();
        } else {
          cityDetailsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      public Builder clearCityDetails() {
        if (cityDetailsBuilder_ == null) {
          cityDetails_ = null;
          onChanged();
        } else {
          cityDetails_ = null;
          cityDetailsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      public City.CityImport.Builder getCityDetailsBuilder() {
        
        onChanged();
        return getCityDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      public City.CityImportOrBuilder getCityDetailsOrBuilder() {
        if (cityDetailsBuilder_ != null) {
          return cityDetailsBuilder_.getMessageOrBuilder();
        } else {
          return cityDetails_ == null ?
              City.CityImport.getDefaultInstance() : cityDetails_;
        }
      }
      /**
       * <code>.CityImport city_details = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          City.CityImport, City.CityImport.Builder, City.CityImportOrBuilder> 
          getCityDetailsFieldBuilder() {
        if (cityDetailsBuilder_ == null) {
          cityDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              City.CityImport, City.CityImport.Builder, City.CityImportOrBuilder>(
                  getCityDetails(),
                  getParentForChildren(),
                  isClean());
          cityDetails_ = null;
        }
        return cityDetailsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StreetImport)
    }

    // @@protoc_insertion_point(class_scope:StreetImport)
    private static final Street.StreetImport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Street.StreetImport();
    }

    public static Street.StreetImport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreetImport>
        PARSER = new com.google.protobuf.AbstractParser<StreetImport>() {
      @java.lang.Override
      public StreetImport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreetImport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreetImport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreetImport> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Street.StreetImport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreetImport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreetImport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014street.proto\032\ncity.proto\"F\n\014StreetImpo" +
      "rt\022\023\n\013street_name\030\001 \001(\t\022!\n\014city_details\030" +
      "\002 \001(\0132\013.CityImportb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          City.getDescriptor(),
        });
    internal_static_StreetImport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StreetImport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreetImport_descriptor,
        new java.lang.String[] { "StreetName", "CityDetails", });
    City.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
